version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080 # HTTP
    depends_on:
      - postgres
    volumes:
      - ".:/opt/app"

  postgres:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
